# nixpacks.toml
# Minimal configuration for Python + Node.js application using uv

# Use the auto-detection for providers but explicitly name them for clarity
providers = ["...", "python"]

# Environment variables
[variables]
NODE_VERSION = "20"
PYTHON_VERSION = "3.13"

# Setup phase
[phases.setup]
nixPkgs = ["...", "uv", "wget", "curl"]
nixLibs = ["...",]
aptPkgs = ["...",]

cmds = [
  "uv venv --seed",
  "uv pip install -e ./'[gui,rag,code_interpreter,python_executor,mcp]'",
  "uv pip install openpyxl"
]

# Start command - use uv to run the application
[start]
cmd = "uv run run_server.py -m $LLM_BASE_URL -k $LLM_API_KEY -l $LLM_MODEL -s 0.0.0.0"
